export const stockList = [
    { name: 'Apple Inc.', symbol: 'AAPL' },
    { name: 'Microsoft Corporation', symbol: 'MSFT' },
    { name: 'Amazon.com Inc.', symbol: 'AMZN' },
    { name: 'Alphabet Inc.', symbol: 'GOOGL' },
    { name: 'Meta Platforms, Inc.', symbol: 'META' },
    { name: 'Tesla, Inc.', symbol: 'TSLA' },
    { name: 'NVIDIA Corporation', symbol: 'NVDA' },
    { name: 'Berkshire Hathaway Inc.', symbol: 'BRK.A' },
    { name: 'Johnson & Johnson', symbol: 'JNJ' },
    { name: 'JPMorgan Chase & Co.', symbol: 'JPM' },
    { name: 'Visa Inc.', symbol: 'V' },
    { name: 'Procter & Gamble Company', symbol: 'PG' },
    { name: 'Walmart Inc.', symbol: 'WMT' },
    { name: 'The Coca-Cola Company', symbol: 'KO' },
    { name: 'The Home Depot, Inc.', symbol: 'HD' },
    { name: 'Pfizer Inc.', symbol: 'PFE' },
    { name: 'Bank of America Corporation', symbol: 'BAC' },
    { name: 'The Walt Disney Company', symbol: 'DIS' },
    { name: 'Netflix, Inc.', symbol: 'NFLX' },
    { name: 'AT&T Inc.', symbol: 'T' },
    { name: 'Exxon Mobil Corporation', symbol: 'XOM' },
    { name: 'Adobe Inc.', symbol: 'ADBE' },
    { name: 'Mastercard Incorporated', symbol: 'MA' },
    { name: 'Verizon Communications Inc.', symbol: 'VZ' },
    { name: 'Chevron Corporation', symbol: 'CVX' },
    { name: 'Cisco Systems, Inc.', symbol: 'CSCO' },
    { name: 'McDonald\'s Corporation', symbol: 'MCD' },
    { name: 'Intel Corporation', symbol: 'INTC' },
    { name: 'Salesforce.com, Inc.', symbol: 'CRM' },
    { name: 'Abbott Laboratories', symbol: 'ABT' },
    { name: 'PepsiCo, Inc.', symbol: 'PEP' },
    { name: 'General Electric Company', symbol: 'GE' },
    { name: 'IBM', symbol: 'IBM' },
    { name: 'Caterpillar Inc.', symbol: 'CAT' },
    { name: '3M Company', symbol: 'MMM' },
    { name: 'UnitedHealth Group Incorporated', symbol: 'UNH' },
    { name: 'Honeywell International Inc.', symbol: 'HON' },
    { name: 'Oracle Corporation', symbol: 'ORCL' },
    { name: 'The Boeing Company', symbol: 'BA' },
    { name: 'Accenture plc', symbol: 'ACN' },
    { name: 'Bristol Myers Squibb', symbol: 'BMY' },
    { name: 'Comcast Corporation', symbol: 'CMCSA' },
    { name: 'The Goldman Sachs Group, Inc.', symbol: 'GS' },
    { name: 'Netflix Inc.', symbol: 'NFLX' },
    { name: 'Facebook, Inc.', symbol: 'FB' },
    { name: 'The Coca-Cola Company', symbol: 'KO' },
    { name: 'General Motors Company', symbol: 'GM' },
    { name: 'Pfizer Inc.', symbol: 'PFE' },
    { name: 'Nike, Inc.', symbol: 'NKE' },
    { name: 'The Travelers Companies, Inc.', symbol: 'TRV' }
  ];
  